# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "clusterName" . }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    role: master
{{ include "timescaledb-helm.labels" . | indent 4 }}
    app.kubernetes.io/component: timescaledb
{{- if .Values.service.primary.labels }}
{{ .Values.service.primary.labels | toYaml | indent 4 }}
{{- end }}
  annotations:
{{ .Values.service.primary.annotations | toYaml | indent 4 }}
spec:
  type: LoadBalancer
  ports:
{{- if .Values.pgBouncer.enabled }}
  - name: pgbouncer
    port: {{ .Values.pgBouncer.port }}
    targetPort: pgbouncer
    protocol: TCP
{{- end }}
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
